backend:
  name: github
  repo: jerryleung16/my-math-notes
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'

site_url: https://jerryleung16.github.io/my-math-notes/
media_folder: "images"
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    extension: "qmd"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{slug}}/index.qmd"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
