name: Render and Publish
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Inkscape (For TikZ)
        run: sudo apt-get update && sudo apt-get install -y inkscape

      - name: Install TinyTeX (For Math)
        uses: quarto-dev/quarto-actions/setup-tinytex@v2

      - name: Render site
        run: quarto render --log-level info

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
