name: Render and deploy Quarto site
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup-quarto@v2

      - name: Render site
        run: quarto render
